version: "3.9"
services:
  db:
    image: mysql:8.0
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci"
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ../shift-api
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: pass
      DB_NAME: app
      TZ: Asia/Tokyo
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    build:
      context: ../shift-web
    working_dir: /workspace
    environment:
      NEXT_PUBLIC_API_BASE: "http://localhost:8000"
    ports:
      - "3000:3000"
    volumes:
      - ../shift-web:/workspace
      - web_node_modules:/workspace/node_modules
      - web_next:/workspace/.next
    command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0"
    depends_on:
      - api

volumes:
  db_data:
  web_node_modules:
  web_next:
